### PR TITLE
Patched Makefile_exe so we have icon embedded

### PR DESCRIPTION
**Pull request by hartmark**
You were right, the icon is missing from the exe-file, this should add it.

Used this as base for getting it to work:
https://bigcode.wordpress.com/2016/12/21/mingw-windows-icon-resource-example/

image

wine explorer is quite low-resolution so please verify on a windows machine that the exe shows the icon embedded

I also agree that the makefile is quite unmaintainable not using any tools :)
I'll try learn cmake some when I get the time as it should be easier to understand

### CODE REVIEW

**Comment by hartmark** [comment]
@induktio  not sure if you alone have notifications on PRs created

**Comment by induktio** [comment]
Yeah didn't notice the makefile also had windres defined there. The same tool also writes the description metadata on executables, otherwise it would show up as having no description on Windows.

**Comment by hartmark** [comment]
Alright, the wine explorer didn't show much else besides the icon. Did it show in Windows?

**Comment by induktio** [comment]
Sure, it looks like it put all of the metadata details there.

**Pull request merged**
